from django.db import migrations

def seed_actividades_economicas(apps, schema_editor):
    ActividadEconomicaCatalog = apps.get_model('core', 'ActividadEconomicaCatalog')

    actividades = [
        # Image 1
        ("1702", "Fabricación de papel y cartón ondulado y de envases de papel y cartón"),
        ("1709", "Fabricación de otros artículos de papel y cartón"),
        ("1811", "Actividades de impresión"),
        ("1812", "Actividades de servicios relacionadas con la impresión"),
        ("1820", "Reproducción de grabaciones"),
        ("1910", "Fabricación de productos de hornos de coque"),
        ("1920", "Fabricación de productos de la refinación del petróleo"),
        ("2011", "Fabricación de sustancias químicas básicas"),
        ("2012", "Fabricación de abonos y compuestos de nitrógeno"),
        ("2013", "Fabricación de plásticos y caucho sintético en formas primarias"),
        ("2021", "Fabricación de plaguicidas y otros productos químicos de uso agropecuario"),
        ("2022", "Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas"),
        ("2023", "Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador"),
        ("2029", "Fabricación de otros productos químicos n.c.p."),
        ("2030", "Fabricación de fibras artificiales"),
        ("2100", "Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico"),
        ("2211", "Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas de caucho"),
        ("2219", "Fabricación de otros productos de caucho"),
        ("2220", "Fabricación de productos de plástico"),
        ("2310", "Fabricación de vidrio y productos de vidrio"),
        ("2391", "Fabricación de productos refractarios"),
        ("2392", "Fabricación de materiales de arcilla para la construcción"),
        ("2393", "Fabricación de otros productos de porcelana y de cerámica"),
        ("2394", "Fabricación de cemento, cal y yeso"),
        ("2395", "Fabricación de artículos de hormigón, cemento y yeso"),

        # Image 2
        ("2396", "Corte, talla y acabado de la piedra"),
        ("2399", "Fabricación de otros productos minerales no metálicos n.c.p."),
        ("2410", "Industrias básicas de hierro y acero"),
        ("2420", "Fabricación de productos primarios de metales preciosos y otros metales no ferrosos"),
        ("2431", "Fundición de hierro y acero"),
        ("2432", "Fundición de metales no ferrosos"),
        ("2511", "Fabricación de productos metálicos para uso estructural"),
        ("2512", "Fabricación de tanques, depósitos y recipientes de metal"),
        ("2513", "Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central"),
        ("2520", "Fabricación de armas y municiones"),
        ("2591", "Forja, prensado, estampado y laminado de metales; pulvimetalurgia"),
        ("2592", "Tratamiento y revestimiento de metales; maquinado"),
        ("2593", "Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería"),
        ("2599", "Fabricación de otros productos elaborados de metal"),
        ("2610", "Fabricación de componentes y tableros electrónicos"),
        ("2620", "Fabricación de computadores y equipo periférico"),
        ("2630", "Fabricación de equipo de comunicaciones"),
        ("2640", "Fabricación de aparatos electrónicos de consumo"),
        ("2651", "Fabricación de equipo de medición, prueba, navegación y control"),
        ("2652", "Fabricación de relojes"),
        ("2660", "Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico"),
        ("2670", "Fabricación de instrumentos ópticos y equipo fotográfico"),
        ("2680", "Fabricación de soportes magnéticos y ópticos"),
        ("2710", "Fabricación de motores, generadores y transformadores eléctricos y aparatos de distribución y control de la energía eléctrica"),
        ("2720", "Fabricación de pilas, baterías y acumuladores"),
        ("2731", "Fabricación de cables de fibra óptica"),
        ("2732", "Fabricación de otros hilos y cables eléctricos"),
        ("2733", "Fabricación de dispositivos de cableado"),

        # Image 3
        ("2740", "Fabricación de equipo eléctrico de iluminación"),
        ("2750", "Fabricación de aparatos de uso doméstico"),
        ("2790", "Fabricación de otros tipos de equipo eléctrico"),
        ("2811", "Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas"),
        ("2812", "Fabricación de equipo de propulsión de fluidos"),
        ("2813", "Fabricación de otras bombas, compresores, grifos y válvulas"),
        ("2814", "Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión"),
        ("2815", "Fabricación de hornos, hogueras y quemadores"),
        ("2816", "Fabricación de equipo de elevación y manipulación"),
        ("2817", "Fabricación de maquinaria y equipo de oficina, excepto computadores y equipo periférico"),
        ("2818", "Fabricación de herramientas de mano motorizadas"),
        ("2819", "Fabricación de otros tipos de maquinaria de uso general"),
        ("2821", "Fabricación de maquinaria agropecuaria y forestal"),
        ("2822", "Fabricación de maquinaria para la conformación de metales y de máquinas herramienta"),
        ("2823", "Fabricación de maquinaria metalúrgica"),
        ("2824", "Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción"),
        ("2825", "Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco"),
        ("2826", "Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros"),
        ("2829", "Fabricación de otros tipos de maquinaria de uso especial"),
        ("2910", "Fabricación de vehículos automotores"),
        ("2920", "Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques"),
        ("2930", "Fabricación de partes, piezas y accesorios para vehículos automotores"),
        ("3011", "Construcción de buques y estructuras flotantes"),
        ("3012", "Construcción de embarcaciones de recreo y deporte"),
        ("3020", "Fabricación de locomotoras y material rodante"),
        ("3030", "Fabricación de aeronaves, naves espaciales y maquinaria conexa"),

        # Image 4
        ("3040", "Fabricación de vehículos militares de combate"),
        ("3091", "Fabricación de motocicletas"),
        ("3092", "Fabricación de bicicletas y de sillones de ruedas para inválidos"),
        ("3099", "Fabricación de otros tipos de equipo de transporte n.c.p."),
        ("3100", "Fabricación de muebles"),
        ("3211", "Fabricación de joyas y artículos conexos"),
        ("3212", "Fabricación de bisutería y artículos conexos"),
        ("3220", "Fabricación de instrumentos musicales"),
        ("3230", "Fabricación de artículos de deporte"),
        ("3240", "Fabricación de juegos y juguetes"),
        ("3250", "Fabricación de instrumentos y materiales médicos y odontológicos"),
        ("3290", "Otras industrias manufactureras n.c.p."),
        ("3311", "Reparación de productos elaborados de metal"),
        ("3312", "Reparación de maquinaria"),
        ("3313", "Reparación de equipo electrónico y óptico"),
        ("3314", "Reparación de equipo eléctrico"),
        ("3315", "Reparación de equipo de transporte, excepto vehículos automotores"),
        ("3319", "Reparación de otros tipos de equipo"),
        ("3320", "Instalación de maquinaria y equipo industriales"),

        # Image 5 (skipped parts of construction, going onto sales)
        ("3510", "Generación, transmisión y distribución de energía eléctrica"),
        ("3520", "Producción de gas; distribución de combustibles gaseosos por tuberías"),
        ("3530", "Suministro de vapor y de aire acondicionado"),
        ("3600", "Captación, tratamiento y distribución de agua"),
        ("3700", "Evacuación de aguas residuales"),
        ("3811", "Recogida de desechos no peligrosos"),
        ("3812", "Recogida de desechos peligrosos"),
        ("3821", "Tratamiento y eliminación de desechos no peligrosos"),
        ("3822", "Tratamiento y eliminación de desechos peligrosos"),
        ("3830", "Recuperación de materiales"),
        ("3900", "Actividades de descontaminación y otros servicios de gestión de desechos"),

        ("4100", "Construcción de edificios"),
        ("4210", "Construcción de carreteras, vías de ferrocarril, puentes y túneles"),
        ("4220", "Construcción de proyectos de servicio público"),
        ("4290", "Construcción de otras obras de ingeniería civil"),
        ("4311", "Demolición"),
        ("4312", "Preparación del terreno"),
        ("4321", "Instalaciones eléctricas"),
        ("4322", "Instalaciones de plomería, calefacción y aire acondicionado"),
        ("4329", "Otras instalaciones para obras de construcción"),
        ("4330", "Terminación y acabado de edificios"),
        ("4390", "Otras actividades especializadas de construcción"),

        # Continuing sales
        ("4510", "Venta de vehículos automotores"),
        ("4520", "Mantenimiento y reparación de vehículos automotores"),
        ("4530", "Venta de partes, piezas y accesorios para vehículos automotores"),
        ("4540", "Venta, mantenimiento y reparación de motocicletas y sus partes, piezas y accesorios"),
        ("4610", "Venta al por mayor a cambio de una retribución o por contrata"),
        ("4620", "Venta al por mayor de materias primas agropecuarias y animales vivos"),
        ("4631", "Venta al por mayor de alimentos excepto para animales"),
        ("4632", "Venta al por mayor de alimentos para animales"),
        ("4633", "Venta al por mayor de tabaco y bebidas"),
        ("4641", "Venta al por mayor de productos textiles, prendas de vestir y calzado"),
        ("4649", "Venta al por mayor de otros enseres domésticos"),
        ("4651", "Venta al por mayor de computadores, equipo periférico y programas informáticos"),
        ("4652", "Venta al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones"),
        ("4653", "Venta al por mayor de maquinaria, equipo y materiales agropecuarios"),
        ("4659", "Venta al por mayor de otros tipos de maquinaria y equipo"),
        ("4661", "Venta al por mayor de combustibles sólidos, líquidos y gaseosos y productos conexos"),
        ("4662", "Venta al por mayor de metales y minerales metalíferos"),
        ("4663", "Venta al por mayor de materiales de construcción, artículos de ferretería y equipo y materiales de fontanería y calefacción"),
        ("4669", "Venta al por mayor de plástico, desperdicios, desechos, chatarra y otros productos n.c.p."),
        ("4690", "Venta al por mayor no especializada"),
        ("4711", "Venta al por menor en comercios no especializados con predominio de la venta de alimentos, bebidas o tabaco"),
        ("4719", "Otras actividades de venta al por menor en comercios no especializados"),
        ("4721", "Venta al por menor de alimentos en comercios especializados"),
        ("4722", "Venta al por menor de bebidas en comercios especializados (licorerías, depósitos de licores, etc.)"),
        ("4723", "Venta al por menor de productos de tabaco en comercios especializados"),
        ("4730", "Venta al por menor de combustibles para vehículos automotores en comercios especializados"),
        ("4741", "Venta al por menor de computadoras, equipo periférico, programas informáticos y equipo de telecomunicaciones en comercios especializados"),
        ("4742", "Venta al por menor de equipo de sonido y de video en comercios especializados"),
        ("4751", "Venta al por menor de productos textiles en comercios especializados"),
        ("4752", "Venta al por menor de artículos de ferretería, pinturas y productos de vidrio en comercios especializados"),
        ("4753", "Venta al por menor de tapices, alfombras y cubrimientos para paredes y pisos en comercios especializados"),
        ("4759", "Venta al por menor de aparatos eléctricos de uso doméstico, muebles, equipo de iluminación y otros enseres domésticos en comercios especializados"),
        ("4761", "Venta al por menor de productos culturales y recreativos en comercios"),
        ("4762", "Venta al por menor de grabaciones de música y de video en comercios"),
        ("4763", "Venta al por menor de equipo de deporte en comercios especializados"),
        ("4764", "Venta al por menor de juegos y juguetes en comercios especializados"),
        ("4771", "Venta al por menor de prendas de vestir, calzado y artículos de cuero en comercios especializados"),
        ("4772", "Venta al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en comercios especializados"),
        ("4773", "Venta al por menor de otros productos nuevos en comercios e especializados"),
        ("4774", "Venta al por menor de artículos de segunda mano"),
        ("4781", "Venta al por menor de alimentos, bebidas y tabaco en puestos de venta y mercados"),
        ("4782", "Venta al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y mercados"),
        ("4789", "Venta al por menor de otros productos en puestos de venta y mercados"),
        ("4791", "Venta al por menor por correo y por Internet"),
        ("4799", "Otras actividades de venta al por menor no realizadas en comercios, puestos de venta o mercados"),

        # Image continuing on transportation
        ("4911", "Transporte interurbano de pasajeros por ferrocarril"),
        ("4912", "Transporte de carga por ferrocarril"),
        ("4921", "Transporte urbano y suburbano de pasajeros por vía terrestre"),
        ("4922", "Otras actividades de transporte por vía terrestre"),
        ("4923", "Transporte de carga por carretera"),
        ("4930", "Transporte por tuberías"),
        ("5011", "Transporte de pasajeros marítimo y de cabotaje"),
        ("5012", "Transporte de carga marítimo y de cabotaje"),
        ("5021", "Transporte de pasajeros por vías de navegación interiores"),
        ("5022", "Transporte de carga por vías de navegación interiores"),
        ("5110", "Transporte de pasajeros por vía aérea"),
        ("5120", "Transporte de carga por vía aérea"),
        ("5210", "Almacenamiento y depósito"),
        ("5221", "Actividades de servicios vinculadas al transporte terrestre"),
        ("5222", "Actividades de servicios vinculadas al transporte acuático"),
        ("5223", "Actividades de servicios vinculadas al transporte aéreo"),
        ("5224", "Manipulación de la carga"),
        ("5229", "Otras actividades de apoyo al transporte"),

        # Crops and Agriculture
        ("0111", "Cultivo de cereales"),
        ("0112", "Cultivo de leguminosas, excepto en organopónicos, hidropónicos y para semillas"),
        ("0113", "Cultivo de raíces y tubérculos, excepto para semillas"),
        ("0114", "Cultivo de hortalizas y melones, excepto en organopónicos, hidropónicos y para semillas"),
        ("0115", "Cultivo de semillas oleaginosas"),
        ("0116", "Cultivo de caña de azúcar"),
        ("0117", "Cultivo de tabaco"),
        ("0118", "Cultivo de plantas de fibra"),
        ("0119", "Cultivo de otras plantas no perennes"),
        ("0121", "Cultivo de uva"),
        ("0122", "Cultivo de frutas tropicales y subtropicales"),
        ("0123", "Cultivo de cítricos"),
        ("0124", "Cultivo de frutas de pepita y de hueso"),
        ("0125", "Cultivo de otros frutos y nueces de árboles y arbustos"),
        ("0126", "Cultivo de frutos oleaginosos"),
        ("0127", "Cultivo de plantas con las que se preparan bebidas"),
        ("0128", "Cultivo de especias y de plantas aromáticas, medicinales y farmacéuticas"),
        ("0129", "Cultivo de plantas perennes n.c.p."),
        ("0130", "Propagación de plantas"),
        ("0141", "Cría de ganado bovino"),
        ("0142", "Cría de ganado equinos"),
        ("0143", "Cría de ovinos y caprinos"),
        ("0144", "Cría de porcinos"),
        ("0145", "Cría de aves de corral"),
        ("0149", "Cría de otros animales"),
        ("0150", "Cultivo de productos agrícolas en combinación con la cría de animales (unidad de producción agrícola mixta)"),
        ("0161", "Actividades de apoyo a la agricultura"),
        ("0162", "Actividades posteriores a la cosecha"),
        ("0163", "Tratamiento de semillas para propagación"),
        ("0164", "Actividades de apoyo a la ganadería"),
        ("0170", "Caza ordinaria, mediante trampas y actividades de servicios conexas"),
        ("0210", "Silvicultura y otras actividades forestales"),
        ("0220", "Extracción de madera"),
        ("0230", "Recolección de productos forestales distintos de la madera"),
        ("0240", "Servicios de apoyo a la silvicultura"),

        # Fishing and Mining
        ("0311", "Pesca marítima"),
        ("0312", "Pesca fluvial y lacustre"),
        ("0321", "Acuicultura marítima"),
        ("0322", "Acuicultura de agua dulce"),
        ("0510", "Extracción de carbón de piedra"),
        ("0520", "Extracción de lignito"),
        ("0610", "Extracción de petróleo crudo"),
        ("0620", "Extracción de gas natural"),
        ("0710", "Extracción de minerales de hierro"),
        ("0721", "Extracción de minerales de uranio y torio"),
        ("0729", "Extracción de minerales metalíferos no ferrosos n.c.p."),
        ("0810", "Extracción de piedra, arena y arcilla"),
        ("0891", "Extracción de minerales para la fabricación de abonos y productos químicos"),
        ("0892", "Extracción de turba"),
        ("0893", "Extracción de sal"),
        ("0899", "Explotación de otras minas y canteras n.c.p."),
        ("0910", "Actividades de apoyo para la extracción de petróleo y gas natural"),
        ("0990", "Actividades de apoyo para la explotación de otras minas y canteras"),

        # Food products
        ("1010", "Elaboración y conservación de carne"),
        ("1020", "Elaboración y conservación de pescado, crustáceos y moluscos"),
        ("1030", "Elaboración y conservación de frutas, legumbres y hortalizas"),
        ("1040", "Elaboración de aceites y grasas de origen vegetal y animal"),
        ("1050", "Elaboración de productos lácteos"),
        ("1061", "Elaboración de productos de molinería"),
        ("1062", "Elaboración de aceite de maíz, almidones y productos derivados de la molinería húmeda de maíz y de los almidones"),
        ("1071", "Elaboración de productos de panadería"),
        ("1072", "Elaboración de azúcar"),
        ("1073", "Elaboración de cacao y chocolate y de productos de confitería"),
        ("1074", "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares"),
        ("1075", "Elaboración de comidas y platos preparados"),
        ("1079", "Elaboración de otros productos alimenticios n.c.p."),
        ("1080", "Elaboración de alimentos balanceados para animales"),
        ("1101", "Destilación, rectificación y mezcla de bebidas alcohólicas espirituosas"),
        ("1102", "Elaboración de vinos"),
        ("1103", "Elaboración de cervezas y de malta"),
        ("1104", "Elaboración de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas"),
        ("1200", "Elaboración de productos de tabaco"),

        # Textiles and Apparel
        ("1311", "Preparación e hilatura de fibras textiles"),
        ("1312", "Tejedura de productos textiles"),
        ("1313", "Acabado de productos textiles"),
        ("1391", "Fabricación de tejidos de punto y ganchillo"),
        ("1392", "Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir"),
        ("1393", "Fabricación de tapices y alfombras"),
        ("1394", "Fabricación de cuerdas, cordeles, bramantes y redes"),
        ("1399", "Fabricación de otros productos textiles n.c.p."),
        ("1410", "Confección de prendas de vestir, excepto prendas de piel y cuero"),
        ("1420", "Fabricación de artículos de piel"),
        ("1430", "Fabricación de artículos de punto y ganchillo"),

        # Leather and Wood
        ("1511", "Curtido y adobo de cueros, adobo y teñido de pieles"),
        ("1512", "Fabricación de maletas, bolsos de mano y artículos de talabartería y guarnicionería"),
        ("1520", "Fabricación de calzado, excepto ortopédico"),
        ("1610", "Aserrado y acepilladura de madera (aserraderos)"),
        ("1621", "Fabricación de hojas de madera para enchapado y tableros a base de madera"),
        ("1622", "Fabricación de partes y piezas de carpintería para edificios y construcciones"),
        ("1623", "Fabricación de recipientes de madera"),
        ("1629", "Fabricación de otros productos de madera; fabricación de artículos de corcho, paja y materiales trenzables"),
        ("1701", "Fabricación de pasta de madera, papel y cartón"),
    ]

    objects = [
        ActividadEconomicaCatalog(
            code=code,
            name=name,
            sort_order=i
        ) for i, (code, name) in enumerate(actividades)
    ]
    ActividadEconomicaCatalog.objects.bulk_create(objects)


def reverse_seed(apps, schema_editor):
    ActividadEconomicaCatalog = apps.get_model('core', 'ActividadEconomicaCatalog')
    ActividadEconomicaCatalog.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actividad_economica_catalog'),
    ]

    operations = [
        migrations.RunPython(seed_actividades_economicas, reverse_seed),
    ]