# Generated by Django 4.2.7 on 2026-03-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_actividades_economicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoFondosCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_selectable', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Destino de los fondos',
                'verbose_name_plural': 'Destinos de los fondos',
                'db_table': 'core_destinos_fondos_catalog',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentoCaptacionCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_selectable', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Instrumento de captación',
                'verbose_name_plural': 'Instrumentos de captación',
                'db_table': 'core_instrumentos_captacion_catalog',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedioPagoCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_selectable', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Medio de pago',
                'verbose_name_plural': 'Medios de pago',
                'db_table': 'core_medios_pago_catalog',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
    ]
