# Generated by Django 4.2.7 on 2026-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_destinofondoscatalog_instrumentocaptacioncatalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadeconomicacatalog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destinofondoscatalog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instrumentocaptacioncatalog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mecanismocambiariocatalog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mediopagocatalog',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
