# Generated by Django 4.2.7 on 2026-03-09 18:03

from django.db import migrations

def fill_catalogs(apps, schema_editor):
    ActividadEconomicaCatalog = apps.get_model('core', 'ActividadEconomicaCatalog')
    InstrumentoCaptacionCatalog = apps.get_model('core', 'InstrumentoCaptacionCatalog')
    DestinoFondosCatalog = apps.get_model('core', 'DestinoFondosCatalog')
    MedioPagoCatalog = apps.get_model('core', 'MedioPagoCatalog')

    actividades = [
        ('5310', 'Actividades postales'),
        ('5320', 'Actividades de mensajería'),
        ('5510', 'Actividades de alojamiento para estancias cortas'),
        ('5520', 'Actividades de campamentos, parques de vehículos de recreo y parques de caravanas'),
        ('5590', 'Otras actividades de alojamiento'),
        ('5610', 'Actividades de restaurantes y de servicio móvil de comidas'),
        ('5621', 'Suministro de comidas por encargo'),
        ('5629', 'Otras actividades de servicio de comidas'),
        ('5630', 'Actividades de servicio de bebidas'),
        ('5811', 'Edición de libros'),
        ('5812', 'Edición de directorios y listas de correos'),
        ('5813', 'Edición de periódicos, revistas y otras publicaciones periódicas'),
        ('5819', 'Otras actividades de edición'),
        ('5820', 'Edición de programas informáticos'),
        ('5911', 'Actividades de producción de películas cinematográficas, videos y programas de televisión'),
        ('5912', 'Actividades de postproducción de películas, videos y programas de televisión'),
        ('5913', 'Actividades de distribución de películas, videos y programas de televisión'),
        ('5914', 'Actividades de proyección de películas'),
        ('5920', 'Actividades de grabación de sonido y edición de música'),
        ('6010', 'Actividades programación y difusión de radio'),
        ('6020', 'Programación y transmisiones de televisión'),
        ('6110', 'Actividades de telecomunicaciones alámbricas'),
        ('6120', 'Actividades de telecomunicaciones inalámbricas'),
        ('6130', 'Actividades de telecomunicaciones por satélite'),
        ('6190', 'Otras actividades de telecomunicación n.c.p.'),
        ('6201', 'Actividades de programación, consultoría informática y actividades conexas'),
        ('6202', 'Actividades de consultoría informática y de gestión de instalaciones informáticas'),
        ('6209', 'Otras actividades de tecnología de la información y de servicios informáticos n.c.p.'),
        ('6311', 'Procesamiento de datos, hosting y actividades conexas'),
        ('6312', 'Portales Web'),
        
        ('6391', 'Actividades de agencias de noticias'),
        ('6399', 'Otros servicios de información n.c.p.'),
        ('6411', 'Servicios del Banco Central'),
        ('6419', 'Servicios de intermediación financiera n.c.p.'),
        ('6420', 'Actividades de societies de cartera'),
        ('6430', 'Fondos y sociedades de inversión'),
        ('6491', 'Otras actividades crediticias'),
        ('6499', 'Otras actividades de servicios financieros n.c.p.'),
        ('6511', 'Servicios de seguros de personas'),
        ('6512', 'Servicios de seguros generales (patrimoniales y de obligaciones y/o responsabilidad)'),
        ('6520', 'Reaseguros'),
        ('6530', 'Fondos de pensiones'),
        ('6611', 'Administración de mercados financieros'),
        ('6612', 'Corretaje de valores y de contratos de productos básicos'),
        ('6619', 'Otras actividades auxiliares de las actividades de servicios financieros'),
        ('6621', 'Evaluación de riesgos y daños'),
        ('6622', 'Servicios de productores de seguros'),
        ('6623', 'Servicios de empresas financiadoras de primas'),
        ('6629', 'Otras actividades auxiliares de las actividades de seguros y fondos de pensiones'),
        ('6630', 'Actividades de gestión de fondos'),
        ('6810', 'Actividades inmobiliarias realizadas con bienes propios o arrendados'),
        ('6820', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata'),
        ('6910', 'Actividades jurídicas'),
        ('6920', 'Actividades de contabilidad, teneduría de libros y auditoría; consultoría fiscal'),
        ('7010', 'Actividades de oficinas centrales'),
        ('7020', 'Actividades de consultoría de gestión empresarial'),
        ('7110', 'Actividades de arquitectura e ingeniería y actividades conexas de consultoría técnica'),
        ('7120', 'Ensayos y análisis técnicos'),
        ('7210', 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería'),
        
        ('7220', 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades'),
        ('7310', 'Publicidad'),
        ('7320', 'Estudios de mercado y encuestas de opinión pública'),
        ('7410', 'Actividades especializadas de diseño'),
        ('7420', 'Actividades de fotografía'),
        ('7490', 'Otras actividades profesionales, científicas y técnicas n.c.p.'),
        ('7500', 'Actividades veterinarias'),
        ('7710', 'Alquiler y arrendamiento de vehículos automotores'),
        ('7721', 'Alquiler y arrendamiento de equipo recreativo y deportivo'),
        ('7722', 'Alquiler de cintas de video y discos'),
        ('7729', 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos'),
        ('7730', 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles'),
        ('7740', 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor'),
        ('7810', 'Actividades de agencias de empleo'),
        ('7820', 'Actividades de agencias de empleo temporal'),
        ('7830', 'Otras actividades de dotación de recursos humanos'),
        ('7911', 'Actividades de agencias de viajes'),
        ('7912', 'Actividades de operadores turísticos'),
        ('7990', 'Otros servicios de reservas y actividades conexas'),
        ('8010', 'Actividades de seguridad privada'),
        ('8020', 'Actividades de servicios de sistemas de seguridad'),
        ('8030', 'Actividades de investigación'),
        ('8110', 'Actividades combinadas de apoyo a instalaciones'),
        ('8121', 'Limpieza general de edificios'),
        ('8129', 'Otras actividades de limpieza de edificios e instalaciones industriales'),
        ('8130', 'Actividades de paisajismo y servicios de mantenimiento conexos'),
        ('8211', 'Actividades combinadas de servicios administrativos de oficina'),
        
        ('8219', 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina'),
        ('8220', 'Actividades de centros de llamadas'),
        ('8230', 'Organización de convenciones y exposiciones comerciales'),
        ('8291', 'Actividades de agencias de cobro y agencias de calificación crediticia'),
        ('8292', 'Actividades de envasado y empaquetado'),
        ('8299', 'Otras actividades de servicios de apoyo a las empresas n.c.p.'),
        ('8411', 'Actividades de la administración pública en general'),
        ('8412', 'Regulación de las actividades de organismos que prestan servicios sanitarios, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social'),
        ('8413', 'Regulación y facilitación de la actividad económica'),
        ('8421', 'Relaciones exteriores'),
        ('8422', 'Actividades de defensa'),
        ('8423', 'Actividades de mantenimiento del orden público y de seguridad'),
        ('8430', 'Actividades de planes de seguridad social de afiliación obligatoria'),
        ('8510', 'Educación inicial y primaria'),
        ('8521', 'Educación media de formación general y técnica'),
        ('8522', 'Educación de formación técnica y profesional'),
        ('8530', 'Educación universitaria'),
        ('8541', 'Enseñanza deportiva y recreativa'),
        ('8542', 'Enseñanza cultural'),
        ('8549', 'Otros tipos de enseñanza n.c.p.'),
        ('8550', 'Actividades de apoyo a la enseñanza'),
        ('8610', 'Servicios hospitalarios'),
        ('8620', 'Servicios médicos y otros especialistas en consultorios'),
        ('8630', 'Servicios de laboratorios clínicos y de diagnóstico por imagen'),
        ('8690', 'Otras actividades relacionadas con la salud humana n.c.p.'),
        ('8710', 'Servicios sociales con alojamiento relacionados con atención a la salud'),
        ('8720', 'Servicios sociales con alojamiento para personas con discapacidad intelectual, enfermedad mental o adicciones'),
        ('8730', 'Servicios sociales con alojamiento para personas mayores y personas con discapacidad'),

        ('8790', 'Otros servicios sociales con alojamiento n.c.p.'),
        ('8810', 'Servicios sociales sin alojamiento para personas mayores y personas con discapacidad'),
        ('8891', 'Servicios de atención a niños, niñas y adolescentes'),
        ('8892', 'Servicios de atención a personas y familias'),
        ('8893', 'Servicios comunitarios de alimentación'),
        ('8894', 'Actividades de emergencia y socorro'),
        ('8895', 'Actividades de beneficencia y otras actividades de apoyo con fines de asistencia social'),
        ('8899', 'Otras actividades de asistencia social sin alojamiento n.c.p.'),
        ('9000', 'Actividades creativas, artísticas y de entretenimiento'),
        ('9101', 'Actividades de bibliotecas y archivos'),
        ('9102', 'Actividades de museos y gestión de lugares y edificios históricos'),
        ('9103', 'Actividades de jardines botánicos y zoológicos y reservas naturales'),
        ('9200', 'Actividades de juegos de azar y apuestas'),
        ('9311', 'Gestión de instalaciones deportivas'),
        ('9312', 'Actividades de clubes deportivos'),
        ('9319', 'Otras actividades deportivas n.c.p.'),
        ('9321', 'Actividades de parques de atracciones y parques temáticos'),
        ('9329', 'Otras actividades de esparcimiento y recreativas n.c.p.'),
        ('9411', 'Actividades de asociaciones empresariales y de empleadores'),
        ('9412', 'Actividades de asociaciones profesionales'),
        ('9420', 'Actividades de sindicatos'),
        ('9491', 'Actividades de organizaciones religiosas'),
        ('9492', 'Actividades de organizaciones políticas'),
        ('9499', 'Actividades de otras asociaciones n.c.p.'),
        ('9511', 'Reparación de computadores y equipo periférico'),
        ('9512', 'Reparación de equipo de comunicaciones'),
        ('9521', 'Reparación de aparatos electrónicos de consumo'),
        ('9522', 'Reparación de aparatos de uso doméstico y equipo doméstico y de jardinería'),
        ('9523', 'Reparación de calzado y de artículos de cuero'),

        ('9524', 'Reparación de muebles y accesorios domésticos'),
        ('9529', 'Reparación de efectos personales y enseres domésticos n.c.p.'),
        ('9601', 'Lavado y limpieza, incluida la limpieza en seco, de productos textiles y de piel'),
        ('9602', 'Peluquería y otros tratamientos de belleza'),
        ('9603', 'Pompas fúnebres y actividades conexas'),
        ('9609', 'Otras actividades de servicios personales n.c.p.'),
        ('9700', 'Actividades de los hogares como empleadores de personal doméstico'),
        ('9810', 'Actividades no diferenciadas de los hogares como productores de bienes para uso propio'),
        ('9820', 'Actividades no diferenciadas de los hogares como productores de servicios para uso propio'),
        ('9900', 'Actividades de organizaciones y órganos extraterritoriales'),
    ]

    for i, (code, name) in enumerate(actividades):
        ActividadEconomicaCatalog.objects.get_or_create(
            code=code,
            defaults={'name': name, 'sort_order': i}
        )

    instrumentos = [
        ('8', 'Depósito de Ahorro'),
        ('9', 'Cuenta Corriente No Remunerada'),
        ('10', 'Cuenta Corriente Remunerada'),
        ('31', 'Cuenta Corriente Sistema de Mercado Cambiario de Libre Convertibilidad'),
        ('32', 'Depósito de Ahorro Sistema de Mercado Cambiario de Libre Convertibilidad'),
    ]
    for i, (code, name) in enumerate(instrumentos):
        InstrumentoCaptacionCatalog.objects.get_or_create(code=code, defaults={'name': name, 'sort_order': i})

    destinos = [
        ('1', 'Materia prima'),
        ('2', 'Sueldos y salarios'),
        ('3', 'Pago a proveedores'),
        ('4', 'Cancelación de Prestamos'),
        ('5', 'Ahorro'),
        ('6', 'Inventario'),
        ('7', 'Pago de Servicios'),
        ('8', 'Honorarios Profesionales'),
        ('10', 'Capital de Trabajo'),
        ('11', 'Mobiliario y Equipos'),
    ]
    for i, (code, name) in enumerate(destinos):
        DestinoFondosCatalog.objects.get_or_create(code=code, defaults={'name': name, 'sort_order': i})

    medios = [
        ('0', 'No Aplica'),
        ('1', 'Retiro en efectivo'),
        ('2', 'Transferencia electrónica a cuenta cliente (nacional)'),
        ('3', 'Transferencia electrónica a cuenta cliente en el exterior (vía corresponsal)'),
    ]
    for i, (code, name) in enumerate(medios):
        MedioPagoCatalog.objects.get_or_create(code=code, defaults={'name': name, 'sort_order': i})

def reverse_catalogs(apps, schema_editor):
    ActividadEconomicaCatalog = apps.get_model('core', 'ActividadEconomicaCatalog')
    InstrumentoCaptacionCatalog = apps.get_model('core', 'InstrumentoCaptacionCatalog')
    DestinoFondosCatalog = apps.get_model('core', 'DestinoFondosCatalog')
    MedioPagoCatalog = apps.get_model('core', 'MedioPagoCatalog')
    
    InstrumentoCaptacionCatalog.objects.all().delete()
    DestinoFondosCatalog.objects.all().delete()
    MedioPagoCatalog.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_actividadeconomicacatalog_name_and_more'),
    ]

    operations = [
        migrations.RunPython(fill_catalogs, reverse_catalogs),
    ]
