# Generated by Django 4.2.7 on 2026-03-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoSubasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_ente_supervisado', models.CharField(help_text='Código comercial asignado por BCV', max_length=4)),
                ('fecha_recepcion_fondos', models.DateTimeField(help_text='Fecha en la que el Ente recibió los fondos del BCV (AAAA-MM-DDTHH:MM:SS.sss)')),
                ('fecha_subasta', models.DateTimeField(help_text='Fecha en la que se realizó la subasta privada (AAAA-MM-DDTHH:MM:SS.sss)')),
                ('codigo_identificacion_subasta', models.CharField(help_text='Código que identifica la subasta privada según BCV', max_length=50)),
                ('tipo_operacion', models.IntegerField(help_text='Código tipo operación (8 o 9)')),
                ('estatus_solicitud_cliente', models.CharField(help_text='SA (Solicitud Aprobada) o SNA (Solicitud No Aprobada)', max_length=3)),
                ('fecha_solicitud_cliente', models.DateTimeField(help_text='Día hábil en el que el cliente realizó la solicitud')),
                ('moneda', models.IntegerField(help_text='Código del tipo de moneda (Distinto a 928)')),
                ('monto_final_divisa', models.DecimalField(decimal_places=4, help_text='Monto final en moneda extranjera', max_digits=20)),
                ('tipo_cambio_final_bs', models.DecimalField(decimal_places=4, help_text='Tipo de cambio final en Bolívares', max_digits=20)),
                ('contravalor_final_bs', models.DecimalField(decimal_places=4, help_text='Contravalor final en Bolívares (Monto * Tipo Cambio)', max_digits=20)),
                ('identificacion_cliente', models.CharField(help_text='RIF o identificación del cliente', max_length=20)),
                ('nombre_cliente', models.CharField(help_text='Nombres y apellidos o razón social', max_length=100)),
                ('actividad_economica_cliente', models.CharField(help_text='Código de actividad económica del cliente', max_length=10)),
                ('codigo_cuenta_moneda_nacional', models.CharField(help_text='Código de cuenta en moneda nacional', max_length=20)),
                ('tipo_cuenta_moneda_nacional', models.IntegerField(help_text='Código tipo cuenta nacional')),
                ('codigo_cuenta_moneda_extranjera', models.CharField(help_text='Código de cuenta en moneda extranjera', max_length=20)),
                ('tipo_cuenta_moneda_extranjera', models.IntegerField(help_text='Código tipo cuenta extranjera')),
                ('destino_fondos', models.IntegerField(help_text='Código destino de los fondos')),
                ('medio_pago', models.IntegerField(help_text='Código medio de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('success', 'Exitoso'), ('rejected', 'Rechazado'), ('corrected', 'Corregido'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resultado de Subasta',
                'verbose_name_plural': 'Resultados de Subasta',
                'db_table': 'resultados_subasta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='resultados__status_4a5677_idx'), models.Index(fields=['codigo_identificacion_subasta'], name='resultados__codigo__918192_idx'), models.Index(fields=['fecha_subasta'], name='resultados__fecha_s_a9c093_idx')],
            },
        ),
    ]
