# Generated by Django 4.2.7 on 2026-06-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operaciones_mesa_de_cambio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operacionmesadecambio",
            name="codigo_operacion",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de identificación único de la operación (API-04)",
                max_length=40,
            ),
        ),
    ]
