# Generated by Django 4.2.7 on 2026-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntervencionTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_ente_supervisado', models.CharField(max_length=4)),
                ('tipo_intervencion', models.CharField(max_length=10)),
                ('fecha_intervencion', models.DateTimeField()),
                ('codigo_identificacion_intervencion', models.CharField(max_length=10, unique=True)),
                ('fecha_operacion_cliente', models.DateTimeField()),
                ('moneda', models.IntegerField()),
                ('identificacion_cliente', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('actividad_economica_cliente', models.CharField(max_length=10)),
                ('monto_divisa', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tipo_cambio_bs', models.DecimalField(decimal_places=4, max_digits=20)),
                ('contravalor_bs', models.DecimalField(decimal_places=4, max_digits=20)),
                ('codigo_cuenta_moneda_nacional', models.CharField(default='0', max_length=20)),
                ('tipo_cuenta_moneda_nacional', models.IntegerField(default=0)),
                ('codigo_cuenta_moneda_extranjera', models.CharField(default='0', max_length=20)),
                ('tipo_cuenta_moneda_extranjera', models.IntegerField(default=0)),
                ('destino_fondos', models.IntegerField()),
                ('medio_pago', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('success', 'Exitoso'), ('rejected', 'Rechazado'), ('corrected', 'Corregido'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intervencion_transacciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='intervencio_status_14887c_idx'), models.Index(fields=['fecha_operacion_cliente'], name='intervencio_fecha_o_c013b6_idx'), models.Index(fields=['codigo_identificacion_intervencion'], name='intervencio_codigo__11d0e6_idx')],
            },
        ),
    ]
