# Generated by Django 4.2.7 on 2026-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubastaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_ente_supervisado', models.CharField(help_text='Código comercial asignado por BCV', max_length=4)),
                ('fecha_subasta', models.DateTimeField(help_text='Fecha en la que se realiza la subasta privada')),
                ('codigo_identificacion_subasta', models.CharField(help_text='Código que identifica la subasta privada según BCV', max_length=50, unique=True)),
                ('fecha_solicitud_cliente', models.DateTimeField(help_text='Día hábil bancario que el cliente realizó la solicitud')),
                ('moneda', models.IntegerField(help_text='Código del tipo de moneda (T003. Moneda)')),
                ('identificacion_cliente', models.CharField(help_text='RIF o identificación del cliente (prefijo + número)', max_length=20)),
                ('nombre_cliente', models.CharField(help_text='Nombres y apellidos o razón social', max_length=100)),
                ('actividad_economica_cliente', models.CharField(help_text='Código de actividad económica (T004)', max_length=10)),
                ('monto_divisa', models.DecimalField(decimal_places=4, help_text='Monto en moneda extranjera solicitado', max_digits=20)),
                ('tipo_cambio_bs', models.DecimalField(decimal_places=4, help_text='Tipo de cambio en Bolívares de la solicitud', max_digits=20)),
                ('contravalor_bs', models.DecimalField(decimal_places=4, help_text='Monto * Tipo Cambio', max_digits=20)),
                ('codigo_cuenta_moneda_nacional', models.CharField(help_text='Código de cuenta en moneda nacional (20 dígitos)', max_length=20)),
                ('tipo_cuenta_moneda_nacional', models.IntegerField(help_text='Código tipo cuenta nacional (T005: 8,9,10)')),
                ('codigo_cuenta_moneda_extranjera', models.CharField(help_text='Código de cuenta en moneda extranjera (20 dígitos)', max_length=20)),
                ('tipo_cuenta_moneda_extranjera', models.IntegerField(help_text='Código tipo cuenta extranjera (T005: 31,32)')),
                ('destino_fondos', models.IntegerField(help_text='Código destino de los fondos (T006)')),
                ('medio_pago', models.IntegerField(help_text='Código medio de pago (T007) - Debe ser 2 para subasta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('success', 'Exitoso'), ('rejected', 'Rechazado'), ('corrected', 'Corregido'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Subasta',
                'verbose_name_plural': 'Solicitudes de Subasta',
                'db_table': 'subasta_solicitudes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='subasta_sol_status_350fe5_idx'), models.Index(fields=['fecha_solicitud_cliente'], name='subasta_sol_fecha_s_75544d_idx'), models.Index(fields=['codigo_identificacion_subasta'], name='subasta_sol_codigo__bf661e_idx'), models.Index(fields=['fecha_subasta'], name='subasta_sol_fecha_s_2b6c0d_idx')],
            },
        ),
    ]
